# Configuration de la base de données MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3307/projet_arbre
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

spring.application.name=projet_arbre
